version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: integreat
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integreat
    ports:
      - "5432:5432"

  backend:
    build: .
    command: ./tools/run.sh
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"